### ISSUE TITLE
View image button no longer visible on CHROME

### ISSUE THREAD

**Issue by BriggsIDP** [bijij/ViewImage#254] opened 2022-06-09 07:55 UTC
**Describe the bug**
Last week the extensions view image button vanished and I've not be able to restore it though uninstalling and reinstalling.

**Screenshots**
![image](https://user-images.githubusercontent.com/107176252/172794820-7c53541c-ccfe-461e-9e5a-d895f78f6409.png)

**System Information**
 - Brave - Version 1.39.120 Chromium: 102.0.5005.99 (Official Build) (64-bit)
 - ViewImage - v3.6.3 (win x86-64) - en_GB

**Comment by funblaster22** [comment] 2022-06-09 22:14
I believe this has been fixed in 3.6.4 (Issue #242) and the Chrome web store just hasn't updated

**Comment by TheCodemonger** [comment] 2022-06-10 19:38
I did some investigation and discovered the following error:
![image](https://user-images.githubusercontent.com/46390896/173132472-9943f28e-762b-42de-a7ab-bd2e8fbd4f32.png)

I was able to trace the likely cause of the nullref back to a switch statement responsible for populating the value of viewImageButtonText - which has no default case. This remains true in the current version of the repo.
```js
// Set the view image button text
    var viewImageButtonText;
    switch (version) {
        case VERSIONS.FEB18:
            viewImageButtonText = viewImageButton.querySelector('.Tl8XHc');
            break;
        case VERSIONS.JUL19:
            viewImageButtonText = viewImageButton.querySelector('.irc_ho');
            break;
        case VERSIONS.OCT19:
            viewImageButtonText = viewImageButton.querySelector('.pM4Snf, .KSvtLc');
            break;
    }
```
'viewImageButtonText' is later passed to 'localiseObject()' as the 'obj' arg. 
While not the root cause of the issue and work needed for this update, can we please follow good coding practices and include default cases in switch statements - or at the very least provide a default value when declaring members?

This is my first dive into the Google page code relevant to this plugin, so I don't know if the above needs updating, but here are two examples of containers using the 'tvh9oe' class. The first is the one we want to target and additionally uses 'BIB1wf', others seem to use 'LRNLRb'. 
```html
<div jsname="CGzTgf" class="tvh9oe BIB1wf" data-tbnid="z4_uU0QB2pe-SM">…</div>
<div jsname="R5S48d" class="tvh9oe LRNLRb" style="display: none; transform: translate3d(445px, 0px, 0px);" aria-hidden="true" data-tbnid="-VCM1w56w6u5VM">…</div>
```

Any further down this rabbit hole and I might as well write my own replacement, lol.

Thank you for continuing to maintain this extension, @bijij! 
I'll be patiently awaiting your fix/update.

**Comment by ner00** [comment] 2022-06-10 21:04
> The UserScript stopped working also

Which one?

**Comment by ner00** [comment] 2022-06-10 21:08
> I did some investigation/debugging and discovered the following error being thrown by the extension in Chrome

Well done. Coding practices are a good rule of thumb, worthless in this case.

> Any further down this rabbit hole and I might as well write my own replacement, lol.

That would be reinventing the wheel, unless you make it dynamic enough to parse the structure regardless of Google's changes - as was the case. Part of the problem here is that people haven't been able or willing to read the history of #242
 
> Thank you for continuing to maintain this extension, @bijij! I'll be patiently awaiting your fix/update.

There is a fix, and there is an update.

If I were @bijij I would leave at least on Chromium-related issue open since closing them perpetuates this problem of users not noticing that the issues has been brought up and solved, yet not available because... `<rant>`Google isn't very good at processing things manually (like vetting Chrome Web Store updates to extensions, although ironically letting the Play store become a cesspool of malware and spyware for mobile devices `</rant>`.

Back to the matter at hand, as mentioned by @funblaster22 this is indeed a duplicate of #242 and every other issue in between, as is this one. In less than 10 days, Google made 2 separate class name changes to their Google Images styling. The dev eventually fixed them but warned Chromium-based users (Chrome, etc) that the vetting process on the side of Google could take as long as 2 weeks, while Firefox would take a couple hours. Firefox users have had their situations solved for a good week now. Chromium-based users are depending on Google for approval or they would need to go through hoops to install an unsigned extension.

Now, while you guys are still having issues, and until the official extension gets vetted by Google, you can use the workaround I provided which builds on top of @bijij own UserScript which I updated and fixed when these issues started. If you want to use the workaround while the extension's update isn't officially available, read here: https://github.com/bijij/ViewImage/issues/242#issuecomment-1139210812

**Comment by tsuliwaensis** [comment] 2022-06-11 02:11
> 

I found your updated UserScript on #242. That one works.

**Comment by tsuliwaensis** [comment] 2022-06-11 02:13
>> The UserScript stopped working also

>Which one?

I was referring to the one on this project, but I found the updated UserScript you posted on #242 that one works.

**Comment by trlkly** [comment] 2022-06-14 03:39
@bijij It would be really nice if @ner00's script were linked on the front page (readme.md)--or better yet, uploaded to the update URL. It seems that the current link goes to version 3.5.0.

**Comment by bijij** [comment] 2022-06-14 11:05
I'll leave this issue open until google approves v3.6.4.

**Comment by firew4lker** [comment] 2022-06-14 15:46
After several uninstallations and installations it seems to be ok.

**Comment by ner00** [comment] 2022-06-15 22:37
@bijij has gotten Google to approve v3.6.5 update, it's working perfectly afaik, **I think** this can now be closed.

**Comment by TeamRainless** [comment] 2023-03-03 22:16
> @bijij has gotten Google to approve v3.6.5 update, it's working perfectly afaik, **I think** this can now be closed.

Umm... NO.

March 2023. Not working again. Looks exactly like the photo in the OP.

**Comment by ner00** [comment] 2023-03-03 23:10
> March 2023. Not working again. Looks exactly like the photo in the OP.

Umm... WORKS FINE.

March 2023. Working just fine, for months now, clearly.

![chrome_C2rslFnN0P](https://user-images.githubusercontent.com/2269603/222852368-9d1aff6a-ca0b-412a-b831-e89f4f1675f6.png)

**Comment by ner00** [comment] 2023-03-03 23:13
> March 2023. Not working again. Looks exactly like the photo in the OP.

Umm... WORKS FINE.

Has been, for months, clearly.

![chrome_eHOk7oYFUg](https://user-images.githubusercontent.com/2269603/222852678-b6ef6f10-c359-4b42-a405-befe9b0b6234.png)

**Comment by TeamRainless** [comment] 2023-03-04 01:37
Not for me...

[image: Screen Shot 2023-03-04 at 2.35.28 AM.png]

**Comment by bijij** [comment] 2023-03-06 12:48
Likely this is another A:B test from google.
Unfortunately the extension is still working for me, so I can't fix it.

PR's welcome

**Comment by vladimirgluten** [comment] 2023-03-06 19:30
> Likely this is another A:B test from google.

This is extremely weird because I just tried it on my 2nd google account and I do have the view image button, but if I use my main account it's not there.  Now I want to know what the difference between the 2 accounts is!

**Comment by vladimirgluten** [comment] 2023-03-10 02:19
And now even weirder, it just started working again using my main google account.  I think I just needed to complain hard enough!

**Comment by TeamRainless** [comment] 2023-03-10 04:43
Mine is still not working. Just uninstalled and re-installed. Nothing.

**Closed** 2024-03-01 13:39 UTC
Labels: bug
