### ISSUE TITLE
View Image button not appearing

### ISSUE THREAD

**Issue by riahc3** [bijij/ViewImage#251] opened 2022-06-04 06:32 UTC
The View Image button not appearing. Seems Google changed something.

**Comment by FranBunnyFFXII** [comment] 2022-06-04 06:50
Same issue here, its been like this for weeks. The button is not appearing. Getting very frustrated as I use this constantly.

**Comment by bijij** [comment] 2022-06-04 21:17
Duplicate of #242 this has been fixed however I'm waiting on google to approve the update for chrome. Could be a few weeks unfortunately.

**Closed** 2022-06-05 05:04 UTC
