### ISSUE TITLE
It doesn't work with new Google Images arrangement to the right side

### ISSUE THREAD

**Issue by jedikalimero** [bijij/ViewImage#218] opened 2020-06-15 14:00 UTC
In the new arrangement of Google Images where the details about an image appear in a black box to the right instead of a black box between lines, ViewImage doesn't seem to do anything. No "View Image" button and no "Search Image" button.

![2020-06-15 (1)](https://user-images.githubusercontent.com/18701653/84666289-d1134b80-af18-11ea-90cc-b7b5d4670435.png)

If I also run Add-on "Google Images Restored" to rearrange Google Images in the old style, it doesn't work either. A "View Image" button appears but this one is added by this other Add-on.

![2020-06-15](https://user-images.githubusercontent.com/18701653/84666320-d96b8680-af18-11ea-8507-a3ef24e8714d.png)

Using Google.com in Spanish.

 - Browser Firefox 
 - Version 77.0.1 (64 bit)

Windows 10 64-bit

**Comment by B00ze64** [comment] 2020-06-28 03:06
I installed  bijij/ViewImage just now, and it works fine with the Right-Side thing on Google. I do NOT see a "Search By Image" button, but I do have a "View Image" button that works. Not sure where the "Search By Image" is supposed to show, that one might be broken...

**Comment by DRSDavidSoft** [comment] 2021-02-12 13:21
I think this is caused by #221, try enabling the **Show Globe icon in "View Image" button** option and see if it works.  I personally also use the right sidebar version of Google, and until enabling that option the button was also missing for me.

**Comment by B00ze64** [comment] 2021-02-13 02:39
I use [Make Google Image Search Great Again](https://github.com/Procyon-b/make-gis-great-again) nowadays with ViolentMonkey, it's updated now and again...

**Comment by bijij** [comment] 2021-08-07 23:50
I believe this has been resolved? closing for now.

**Closed by bijij** 2021-08-07 23:50 UTC
Labels: bug
