### ISSUE TITLE
No longer works on Mozilla Firefox

### ISSUE THREAD

**Issue by Marridreg** [bijij/ViewImage#156] opened 2018-08-16 15:14 UTC
Using Windows 10, Acer Aspire V laptop.

**Comment by WolfganP** [comment] 2018-08-16 19:08
Same here on 62.0b17 (windows10), but it's not permanent (some searches the button appears, others don't)

**Comment by bijij** [comment] 2018-08-21 12:05
I'm going to assume this was a duplicate of #154

**Closed by bijij** 2018-08-21 12:05 UTC
Labels: duplicate
