### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Lewandelein** [bijij/ViewImage#93] opened 2018-02-27 14:46 UTC
Hi, first of all thank you for creating this addon. Unfortunately I could not install it as others in the past 14 hours too. It gives me this message (sorry it is partialy in german) 

Paket ist ungültig. Details: "Messages file is missing for locale. C:\Users\Katka\AppData\Local\Temp\scoped_dir2372_1747\CRX_INSTALL\_locales\ru\messages.json"

Is it possible there is a problem on my part?  thank you for your answer in advance

Katerina

**Comment by 95deepan** [comment] 2018-02-27 17:04
which browser are you using?

**Comment by Lewandelein** [comment] 2018-02-27 18:07
Google Chrome

Dne 27. 2. 2018 18:04 napsal uživatel "Deepan kumar C" <
notifications@github.com>:

which browser are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bijij/ViewImage/issues/93#issuecomment-368950745>, or mute
the thread

**Comment by needforsuv** [comment] 2018-02-28 00:54
Same as #90

**Comment by bijij** [comment] 2018-02-28 05:01
Is this still a problem? I rolled out a fix about that time.

**Comment by bijij** [comment] 2018-02-28 05:03
Also duplicate of #90

**Closed by bijij** 2018-02-28 05:03 UTC
