### ISSUE TITLE
Cant use For High resolution images

### ISSUE THREAD

**Issue by Rajastikle** [bijij/ViewImage#53] opened 2018-02-20 06:33 UTC
hey its not working for more than 4000 X 4000 images
is there any other application... for that or solution

**Comment by thinkpad4** [comment] 2018-02-20 06:57
I noticed that too, any chance of a fix?

**Comment by bijij** [comment] 2018-02-20 07:20
duplicate of #52 
Fixed in next release.

**Closed** 2018-02-20 07:20 UTC
Labels: bug
