### ISSUE TITLE
ViewImage does not work in Chrome Beta

### ISSUE THREAD

**Issue by adanvdo** [bijij/ViewImage#249] opened 2022-06-02 14:39 UTC
**Describe the bug**
the ViewImage button is no longer displayed in the latest Chrome beta.

**To Reproduce**
Perform an Image search.
Click on an Image.
The only button displayed is "Visit"

**Expected behavior**
The View Image button should be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/26498008/171654566-b6db934f-2c44-43e9-8856-d74e29c12ca7.png)

**System Information**
 - Browser Chrome
 - Version 103.0.5060.33 (Official Build) beta (64-bit)

**Additional context**
I noticed this a few days ago. Most people probably use the stable Chrome builds, so hopefully this gives you a head start.

**Comment by ner00** [comment] 2022-06-02 15:50
Is it specific to the beta version or is it not working in Chrome at all?

**Comment by adanvdo** [comment] 2022-06-02 15:54
> Is it specific to the beta version or is it not working in Chrome at all?

Just installed Chrome Version 102.0.5005.63 (Official Build) (64-bit) to check. 
Can confirm it is not working at all.

![image](https://user-images.githubusercontent.com/26498008/171671793-0ccc138d-a3b8-46e5-8e0e-30d5b83595b7.png)

**Comment by ner00** [comment] 2022-06-02 17:06
This seems to be a duplicate of #242, please refer to this comment by the dev: https://github.com/bijij/ViewImage/issues/242#issuecomment-1144666979

...in which the dev explains that the updated extension may take a week to be updated by Google. For a temporary workaround, see this: https://github.com/bijij/ViewImage/issues/242#issuecomment-1139210812

**Closed** 2022-06-03 00:12 UTC
Labels: bug
