### ISSUE TITLE
"Search Google for Image"-results doesn't have the view image button

### ISSUE THREAD

**Issue by MrDemocracy** [bijij/ViewImage#20] opened 2018-02-17 10:51 UTC
The view image button is not visible on "Search Google for Image"-results.

Example screenshot:
<img width="1280" src="https://user-images.githubusercontent.com/23060864/36340214-92b29c8e-13d8-11e8-88e9-98fbf13cb330.png">

**Comment by bijij** [comment] 2018-02-17 11:28
Can you tell me what version you are using?
An upcoming update might fix these issues.

**Comment by MrDemocracy** [comment] 2018-02-17 11:38
Version 1.4

**Comment by bijij** [comment] 2018-02-17 11:43
Can you tell me what you googled to get to that image?
Might be an issue with "Getty images" in particular though.

**Comment by MrDemocracy** [comment] 2018-02-17 12:17
I right clicked an image similar to the image you can see in the screenshot, and clicked the "Search Google for Image" option in Google Chrome (idk if any other browsers has this feature by default).
[Here's the link](https://www.google.com/imgres?imgurl=https://media.gettyimages.com/photos/josefine-pettersen-and-iman-meskini-attend-skam-photocall-during-the-picture-id867420092%3Fs%3D612x612&imgrefurl=http://www.gettyimages.fi/photos/skam&h=408&w=612&tbnid=lAsSUUOz0aMVSM&tbnh=183&tbnw=275&usg=__GPcNEq7awEwKYHL-RdD4MXrhRPQ=&hl=en-NO&docid=9q4vW90W3A_Z7M&itg=1) to the page of my first example screenshot:
The same thing also happens for any image file i drag and drop to the google search text box.
<img width="869" src="https://user-images.githubusercontent.com/23060864/36340781-dff18eb4-13e3-11e8-93fc-12dde53aece8.png">

**Comment by bijij** [comment] 2018-02-17 12:32
![chrome_2018-02-17_22-30-23](https://user-images.githubusercontent.com/8677174/36340940-4851969a-1432-11e8-8a9a-447c43cb8f19.png)
Fixed in commit 0ecfe2db8b57f9526872c9f7c8b88743f5fb52dc 

Will publish live to Chrome and Firefox stores later today.

**Comment by MrDemocracy** [comment] 2018-02-17 12:34
Yay 😄

**Comment by MrDemocracy** [comment] 2018-02-17 18:06
I just updated to version 1.5.3 now. 
When I click the "View image" button on a similar page to where it didn't work before, it just opens the same Google image preview page, without the "View image" button.
[Link](https://www.google.no/imgres?imgurl=https://media2.giphy.com/media/ddEl1Ey8A58OI/giphy.gif&imgrefurl=https://giphy.com/explore/i-dont-like-to-feel-good&h=373&w=500&tbnid=N2j2kpFo8DWhpM&tbnh=194&tbnw=260&usg=__JfqoYgTYpUs33QRAklsYNpxgvTk=&hl=no&docid=xT6yHhXkWVk6nM).

**Comment by bijij** [comment] 2018-02-17 18:07
If you refresh the pages does it display, can't check right now. If not
I'll look into it tomorrow.

**Comment by MrDemocracy** [comment] 2018-02-17 18:09
It does not load the button even when I refresh the page.

**Comment by filips123** [comment] 2018-02-18 17:07
Search by Image is also not working.

**Comment by bijij** [comment] 2018-02-18 17:11
Could you tell me what browser you're using, version info, and whether this still happens with other extensions disabled.

Can't seem to replicate.

**Comment by bijij** [comment] 2018-02-18 17:31
Can you paste that url?

**Comment by MrDemocracy** [comment] 2018-02-18 17:32
[URL](https://www.google.no/imgres?imgurl=https://media2.giphy.com/media/ddEl1Ey8A58OI/giphy.gif&imgrefurl=https://giphy.com/explore/i-dont-like-to-feel-good&h=373&w=500&tbnid=N2j2kpFo8DWhpM&tbnh=194&tbnw=260&usg=__JfqoYgTYpUs33QRAklsYNpxgvTk=&hl=en-NO&docid=xT6yHhXkWVk6nM)

**Comment by filips123** [comment] 2018-02-18 17:34
I use Firefox and Chrome. View Image version 1.5.5.
This work on normal Google Images, but not on https://www.google.no/imgres?imgurl=https://media2.giphy.com/media/ddEl1Ey8A58OI/giphy.gif&imgrefurl=https://giphy.com/explore/i-dont-like-to-feel-good&h=373&w=500&tbnid=N2j2kpFo8DWhpM&tbnh=194&tbnw=260&usg=__JfqoYgTYpUs33QRAklsYNpxgvTk=&hl=no&docid=xT6yHhXkWVk6nM
In Firefox, if I click View Image button, the same page opens in new tab. If I click Search by Image it opens https://www.google.si/imghp?sbi=1.
In Chrome, there is no View Image button.

Screenshots:
Chrome - http://oi67.tinypic.com/2mctxsn.jpg
Firefox - http://sendvid.com/br1pr8ar

**Comment by bijij** [comment] 2018-02-19 05:18
I'll take a look later on today. See if I can figure out what the root of the problem is.

**Comment by bijij** [comment] 2018-02-19 05:18
Up

**Comment by bijij** [comment] 2018-02-19 11:56
![image](https://user-images.githubusercontent.com/8677174/36376696-b6fda276-15bf-11e8-8f3d-8075702c34c2.png)

Seems to be fixed with that commit. Will publish as version 1.6.0 later today.

**Comment by filips123** [comment] 2018-02-19 12:52
This now work in Firefox, but not in Chrome.
If I open image directly from [URL](https://www.google.no/imgres?imgurl=https://media2.giphy.com/media/ddEl1Ey8A58OI/giphy.gif&imgrefurl=https://giphy.com/explore/i-dont-like-to-feel-good&h=373&w=500&tbnid=N2j2kpFo8DWhpM&tbnh=194&tbnw=260&usg=__JfqoYgTYpUs33QRAklsYNpxgvTk=&hl=no&docid=xT6yHhXkWVk6nM) or from [Google Search](https://www.google.si/search?q=google&oq=google&aqs=chrome..69i57j69i60l5.3736j0j7&sourceid=chrome&ie=UTF-8) it don't display View Image button and Search by Image link. If I reload page several times, it's working again.
I use version 1.6.0.
screenshot - http://sendvid.com/4b7ea0kl

**Comment by bijij** [comment] 2018-02-19 12:53
Chrome is on 1.6?

**Comment by filips123** [comment] 2018-02-19 12:54
Yes.
https://chrome.google.com/webstore/detail/view-image/jpcmhcelnjdmblfmjabdeclccemkghjk

**Comment by bijij** [comment] 2018-02-19 12:55
so in `chrome://extensions` it displays as version 1.6? I cannot reproduce this on 1.6

**Comment by filips123** [comment] 2018-02-19 12:57
Yes
![slika](https://user-images.githubusercontent.com/16626308/36378840-cb92e612-157c-11e8-9306-231aff09ceec.png)

**Comment by bijij** [comment] 2018-02-19 12:59
If you clone the source and load as an unpacked extension. do any errors occur when you load the page?
Also does this occur with no other extensions running?

**Comment by filips123** [comment] 2018-02-19 13:10
There are no errors in the console. I installed the extension from Chrome Webstore.
When I have all extensions, except View Image disabled, it works normally. However, when I have enabled other extensions, it does not work.

**Comment by bijij** [comment] 2018-02-19 13:11
If you can figure out which extension is causing the issue. I'll see if I
can do anything about it.

**Comment by filips123** [comment] 2018-02-19 13:14
My extensions:
[Adobe Acrobat](https://chrome.google.com/webstore/detail/adobe-acrobat/efaidnbmnnnibpcajpcglclefindmkaj?utm_source=chrome-app-launcher-info-dialog)
[Avast Online Security](https://chrome.google.com/webstore/detail/avast-online-security/gomekmidlodglbbmalcneegieacbdmki?utm_source=chrome-app-launcher-info-dialog)
[BuiltWith Technology Profiler](https://chrome.google.com/webstore/detail/builtwith-technology-prof/dapjbgnjinbpoindlpdmhochffioedbn?utm_source=chrome-app-launcher-info-dialog)
[Skype Calling](https://chrome.google.com/webstore/detail/skype-calling/poghlonenmjdkfghdpfomojhhfggildk?utm_source=chrome-app-launcher-info-dialog)
[Office Online](https://chrome.google.com/webstore/detail/office-online/ndjpnladcallmjemlbaebfadecfhkepb?utm_source=chrome-app-launcher-info-dialog)
[Page Analytics (by Google)](https://chrome.google.com/webstore/detail/page-analytics-by-google/fnbdnhhicmebfgdgglcdacdapkcihcoh?utm_source=chrome-app-launcher-info-dialog)
[Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?utm_source=chrome-app-launcher-info-dialog)
[uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?utm_source=chrome-app-launcher-info-dialog)

**Comment by filips123** [comment] 2018-02-19 13:16
I think this is because Adobe Acrobat.

**Comment by bijij** [comment] 2018-02-19 13:34
Buttons all still seem to appear as normal with Acrobat Extension.

Maybe a Tampermonkey script? or Avast?

**Comment by filips123** [comment] 2018-02-19 13:48
If I have Adobe Acrobat enabled sometimes work and sometimes not. If I have it disabled it works.

**Comment by bijij** [comment] 2018-02-19 13:52
Refreshing the page 20 times was able to reproduce once with Acrobat. I'll see if I can do anything about it.

**Comment by bijij** [comment] 2018-02-19 14:31
After doing some investigating, I think I found the issue to be related to the observer firing before the DOM had finished loading.

4383314875a8f1d872d5d03b435fdbe682de623e *should* fix this.

@filips123 if you could please clone the source again and confirm?

**Comment by filips123** [comment] 2018-02-19 16:36
I tested it and now is working.

**Comment by bijij** [comment] 2018-02-19 16:37
Awesome I'll publish this now then

**Closed by bijij** 2018-02-19 16:37 UTC
Labels: bug
