### ISSUE TITLE
ViewImage extension no longer working in Firefox

### ISSUE THREAD

**Issue by davidtderrick** [bijij/ViewImage#245] opened 2022-05-29 22:04 UTC
ViewImage extension no longer working in Firefox 101.0 for Mac.

**Comment by Reonu** [comment] 2022-05-30 02:20
Same here on W11

**Comment by payam-pawapay** [comment] 2022-05-30 14:35
Also Chrome & Mac

**Comment by affinage** [comment] 2022-05-30 14:51
same here. 
firefox 99.0.1 @ mac os high sierra 10.13.4

**Comment by ner00** [comment] 2022-05-30 15:45
https://github.com/bijij/ViewImage/issues/242

**Comment by softyoda** [comment] 2022-06-01 13:52
Same here Version 101.0 (64 bits)

**Comment by ner00** [comment] 2022-06-01 15:06
> Same here Version 101.0 (64 bits)

It's still a duplicate of https://github.com/bijij/ViewImage/issues/242  though...

**Comment by ner00** [comment] 2022-06-01 15:25
> Ok, thanks, but I didn't get the thread of #242 Will this extension be deprecated, and we should install Greasemonkey?

I'm not sure, no reason to think it will be deprecated, it has been less than a week and the dev might not have had the time to review this. The workaround I provided is just in case you want to bring the main functionality back while you wait for an official fix.

**Comment by softyoda** [comment] 2022-06-01 15:34
Oh, ok, sorry, thank you for your help :) I will continue with the firefox extention when it will update then. Thanks.

**Comment by MereMoon** [comment] 2022-06-02 01:21
> > Ok, thanks, but I didn't get the thread of #242 Will this extension be deprecated, and we should install Greasemonkey?
> 
> I'm not sure, no reason to think it will be deprecated, it has been less than a week and the dev might not have had the time to review this. The workaround I provided is just in case you want to bring the main functionality back while you wait for an official fix.

Hello, the workaround has now stopped working as well.

**Comment by ner00** [comment] 2022-06-02 11:52
Fixed the custom script mentioned [here](https://github.com/bijij/ViewImage/issues/242#issuecomment-1139210812), update directly by clicking [here](https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3/raw/viewimage.user.js).

**Comment by ner00** [comment] 2022-06-02 13:53
This issue should be closed now, it was already a duplicate of #242 but also given that the last fix/update to the extension has already been published to Mozilla's Firefox Add-Ons site and solves this issue.

**Closed** 2022-06-03 00:13 UTC
