### ISSUE TITLE
No search by image button

### ISSUE THREAD

**Issue by Fenir8** [bijij/ViewImage#14] opened 2018-02-17 03:43 UTC
Hello, I tried out your extension after trying a similar one recently. However, I don't see the search by image button in any of my searches?

**Comment by danielhickman** [comment] 2018-02-17 03:53
It currently isn't a button, though making it one may be a good discussion to have for consistency, and is instead a link under the title. I believe this matches the previous behavior from Google.

![image](https://user-images.githubusercontent.com/5341898/36337750-c2d5ccdc-1352-11e8-8288-b7d6357c8982.png)

If you still don't see it, could you comment your browser and extension versions?

**Comment by danielhickman** [comment] 2018-02-17 07:57
I found a review for Firefox that matches this issue and figured I'd quote it since it includes images.

> "Search by image" button is not present: http://i.share.pho.to/b8cf141b_o.png
>
> But it's here for some images while "View image" button duplicates: http://i.share.pho.to/e4809455_o.png
>
> And sometimes there's no new buttons, but if I select another image it may have it and they stay in place if i go back to previous one.
>
> by Anonymous user 586c0d, 14 hours ago

It doesn't list their versions and I can't yet reproduce it.

**Comment by bijij** [comment] 2018-02-17 12:42
Might be related to issue #20 if so, this will have been fixed in 0ecfe2db8b57f9526872c9f7c8b88743f5fb52dc 

will need to confirm though.

**Comment by bijij** [comment] 2018-02-19 16:59
Going to assume this issue was fixed in `1.6.1`

**Closed by bijij** 2018-02-19 16:59 UTC
Labels: bug
