### ISSUE TITLE
Firefox addon doesn't work with version 56.

### ISSUE THREAD

**Issue by CatmanFan** [bijij/ViewImage#2] opened 2018-02-16 17:32 UTC
I already installed the addon, but the View image button doesn't show up, even after I restarted Firefox. I am using version 56.0 (32 bit), which is one of the last "original" Firefox versions before the release of Firefox Quantum.
Is there any chance that compatibility for Firefox 56 can be added please?

**Comment by danielhickman** [comment] 2018-02-17 00:26
Reproduced in version 1.2 and appears to be fixed in version 1.3. 

![image](https://user-images.githubusercontent.com/5341898/36335534-8dd1ba54-1335-11e8-863b-6746185847e6.png)

**Comment by bijij** [comment] 2018-02-17 01:47
I believe this was indeed fixed in 1.3. 
Works as intended on Firefox 56 for me.

**Closed by bijij** 2018-02-17 01:47 UTC
