### ISSUE TITLE
View Image button disappeared in the latest Chrome

### ISSUE THREAD

**Issue by artquest** [bijij/ViewImage#247] opened 2022-06-01 14:02 UTC
View Image button disappeared in the latest Chrome.

![Snap16](https://user-images.githubusercontent.com/24230703/171423115-133c9724-e543-4577-a199-e85f6da15f5f.png)

**Comment by ner00** [comment] 2022-06-01 19:27
Duplicate of https://github.com/bijij/ViewImage/issues/242

**Closed** 2022-06-02 09:41 UTC
Labels: bug
