### ISSUE TITLE
Not working with new layout. Please fix :(

### ISSUE THREAD

**Issue by inspacenyc** [bijij/ViewImage#185] opened 2019-09-12 01:27 UTC
Not working with new layout. Please fix :(

**Comment by Scott274** [comment] 2019-09-23 19:29
View Image button sometimes work but mostly doesn't for me too in the new layout where the image preview opens on the right hand side....Search by Image totally doesn't work anymore. I've send feedback to Google (located right at the bottom) requesting to take me back to the old pull down image preview format..

**Comment by bijij** [comment] 2019-10-26 14:41
Perhaps a duplicate of #181 ?
or I'm guessing just more evidence of google doing a staggered roll-out of changes like seen in #188 and #191

**Comment by bijij** [comment] 2019-11-01 16:44
Gonna close for now. Hoping this has been rectified by my recent changes.

**Closed by bijij** 2019-11-01 16:44 UTC
