### ISSUE TITLE
Doesn't work with Pale Moon

### ISSUE THREAD

**Issue by psychonaut25** [bijij/ViewImage#57] opened 2018-02-21 17:48 UTC
I'm using Pale Moon browser which is a fork of Firefox and it doesn't support WebExtensions.  Would you consider creating a ViewImage Greasemonkey script?

**Comment by bijij** [comment] 2018-02-21 18:12
Hi I have created an unside [XUL](../tree/xul) version of this extension as well as a [userscript](https://gist.github.com/bijij/58cc8cfc859331e4cf80210528a7b255)

**Comment by bijij** [comment] 2018-02-21 18:13
Closing as likley a duplicate of #45

**Closed** 2018-02-21 18:13 UTC
Labels: question

**Comment by psychonaut25** [comment] 2018-02-21 18:24
Thank you!
