### ISSUE TITLE
Does not work for large images

### ISSUE THREAD

**Issue by needforsuv** [bijij/ViewImage#190] opened 2019-10-25 05:28 UTC
Large Images (since google removed more sizes) do not work correctly even with advanced search (using view images only opens the raw Data:thumbnail)

example:
https://www.google.com/search?as_st=y&tbm=isch&hl=en&as_q=twister+game+board&as_epq=&as_oq=&as_eq=&cr=&as_sitesearch=&safe=images&tbs=isz:lt,islt:70mp

click any image to see

HOWEVER, I believe this can easily be fixed by reading the link before even clicking into the image like what I assume this extension does, opening them without invoking the image pane, which it isn't too workable.
https://chrome.google.com/webstore/detail/straight-to-full-size-for/ghhmhdkbiodiengmhbbpjkcjodingned

Specifically, the href already contains the image url in full 

like this (in between imgurl= and &imgrefurl) that only requires basic decoding to convert into a usable link
https://www.google.com/imgres?imgurl=https%3A%2F%2Fi1.wp.com%2Fraelynwebster.smugmug.com%2FPets%2FBoy-Scouts%2FDog-Care-Merit-Badge%2Fi-hMWzhMj%2F0%2FO%2FGame%2520Board.jpg&imgrefurl=https%3A%2F%2Fwearetheowls.wordpress.com%2F2013%2F06%2F10%2Fdog-care-merit-badge-board-game-for-requirements-3-6-7%2F&docid=w9YdNSW7C6bx_M&tbnid=eh6iuH7VF1ywLM%3A&vet=10ahUKEwjL5u-D1bblAhWt8HMBHWd0DocQMwgtKAIwAg..i&w=10800&h=7201&hl=en&safe=images&bih=836&biw=1635&as_q=twister%20game%20board&ved=0ahUKEwjL5u-D1bblAhWt8HMBHWd0DocQMwgtKAIwAg&iact=mrc&uact=8

**Comment by bijij** [comment] 2021-08-07 23:51
Duplicate of likely #131 and #169

**Closed by bijij** 2021-08-07 23:51 UTC
