### ISSUE TITLE
Does not work anymore last firefox version 

### ISSUE THREAD

**Issue by softyoda** [bijij/ViewImage#193] opened 2019-10-26 20:33 UTC
It does not work on firefox 70.0 (64 bits)

**Comment by IB38** [comment] 2019-10-26 21:14
Same for me, FF 70.0 64bit.

**Comment by joel-tonuri** [comment] 2019-10-27 02:16
Same here. Not working. FF 70.0, 64 bit.

**Comment by bijij** [comment] 2019-10-27 03:30
Duplicate of #188

**Closed by bijij** 2019-10-27 03:30 UTC
Labels: duplicate
