### ISSUE TITLE
View Image no longer works when logged into Google on Firefox

### ISSUE THREAD

**Issue by zleonov** [bijij/ViewImage#268] opened 2023-03-20 01:18 UTC
**Describe the bug**
View Image stopped working in Firefox. After trying to debug the issue, I noticed that works in private mode.

That gave me a clue, so I cleared all my cache and it started working again. Then all of a sudden it stopped. I realized that it stops working once you login into your Google account. Clearing the history completely makes it work again, until the next time you login.

So it must be something in the cache or a cookie. I have replicated the issue on several computers, so it doesn't look like it's specific to my setup.

**System Information**
 - Browser: Firefox
 - Version: 111.0

**Comment by zleonov** [comment] 2023-03-20 01:30
*Update*

It seems that it may be related to my particular Google account. I used a different account in Edge and it worked fine. But when I logged into my account in Edge, it stopped working until I logged out, then it was working again.

So it's not a matter of simply being logged in, it's my particular account. Let me know if i can help you debug.

**Comment by ner00** [comment] 2023-03-20 01:34
This has been happening to quite a few users, unfortunately dev wasn't able to reproduce it yet due to the "random" nature of the bug - https://github.com/bijij/ViewImage/issues/254#issuecomment-1456071397

**Comment by zleonov** [comment] 2023-03-20 01:44
If this is at all useful, I tried this Edge addon: https://microsoftedge.microsoft.com/addons/detail/view-image-button/jhglddilleefffeidcidhgaijkgjokfe, and while it works:

When I am logged in, it looks like this (pay attention to the _View image_ text not being centered on the button):
![view_image1](https://user-images.githubusercontent.com/6221648/226227732-56c01e10-40bc-40de-92a6-0ea249069f0e.jpg)

When I am logged out, it works normal:
![view_image2](https://user-images.githubusercontent.com/6221648/226227763-e51e8b21-26ff-4033-b397-84b8b083a61e.jpg)

Would it be useful to save the page to desktop and attach it here?

**Comment by ner00** [comment] 2023-03-20 02:16
@bijij I have now been able to replicate this on accident. I opened Google in Edge without any account and went to the Search settings and changed the language to English and saved, after that there was no more button. I tried using the userscript to debug, it appears to fail when parsing the data source and creating the source images array, but since you're the expert on the matter have a look at this:

![msedge_qMBscbpelB](https://user-images.githubusercontent.com/2269603/226230680-d5d0340a-5bcb-4489-a73c-feec45784816.png)


Some HTML just in case: https://gist.githubusercontent.com/ner00/da32f5958d2e67ba08c0d3e8e4a476de/raw/2313c836812e88af37ae2334348f9008ed810c6a/google_images.html

**Comment by ner00** [comment] 2023-03-20 03:06
I think I found the class that changed, but not sure if someone else can corroborate this.
Before it was (and some times still is) class `n3VNCb` but now I'm seeing class `r48jcc`, and adding that class to the script allows the data source to be processed.

If someone can try this, do the following:

Search an image and above the *Visit* button, in the image preview square, right-click and *Inspect*, see if it highlights something like this: `<img src="https://cdn.mos.cms.futurecdn.net/xXp45gLeBTBt4jPuZcawUJ-1200-80.jpg" jsaction="VQAsE" class="r48jcc pT0Scc iPVvYb" style="max-width: ...`

the important part would be `class="r48jcc pT0Scc iPVvYb"`, specifically the first class `r48jcc`, just to see if this is one variation of many or if everyone getting the failure as the same new class name.

**Comment by zleonov** [comment] 2023-03-20 03:58
@ner00 I am getting **_r48jcc pT0Scc iPVvYb_** when I am logged in and **_n3VNCb pT0Scc KAlRDb_** when in private mode.

Which explains the behavior I am seeing.

The old class _n3VNCb_... is detected while the new class _r48jcc_... is not.

**Comment by ner00** [comment] 2023-03-20 04:06
@zleonov can you try to confirm the visit button class too?

**Comment by zleonov** [comment] 2023-03-20 04:15
@ner00 confirmed. Same as you got: **_Rp89He legCh legCh_** for the outer div and **_Is9g1b K8E1Be cS4Vcb-pGL6qe-lfQAOe dCBVl K8E1Be cS4Vcb-pGL6qe-lfQAOe_** for the inner span.

It does not seem to change whether I am logged in or not.

**Comment by ner00** [comment] 2023-03-20 04:19
That's the class from the `div`, you need to check the class from the parent `a`

**Comment by zleonov** [comment] 2023-03-20 04:23
Same as yours when logged in: **_uZ49bd hsGDOd_**
But in a private window it's: **_jAklOc hsGDOd_**

**Comment by ner00** [comment] 2023-03-20 13:01
That clarifies the issue.
Now we must wait for the dev to push an update, but what's worse is the time Chrome Store takes to approve extensions and updates.

**Comment by ner00** [comment] 2023-03-20 14:04
In the meantime, I updated the script to be used with extensions such as GreaseMonkey, TamperMonkey, etc. You can grab the script here: https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3

**NOTE:** The script linked above will **not** work if the extension is running at the same time. While the extension isn't updated, you can disable it and use the script instead.


For those who might not know how to install user scripts to run in your browser, like an extension, follow this:

1. Make sure to disable or uninstall the View Image extension in your browser (go to settings, find the section with extensions, and disable or uninstall it).
    - Firefox extensions URL: `about:addons`
    - Chrome extensions URL: `chrome://extensions/`
    - Edge extensions URL: `edge://extensions/`

2. Install an extension that allows to add user scripts, most popular are Tampermonkey and Greasemonkey (choose one):

    - Tampermonkey for Firefox: https://addons.mozilla.org/firefox/addon/tampermonkey/
    - Greasemonkey for Firefox: https://addons.mozilla.org/firefox/addon/greasemonkey/
    - Tampermonkey for Chrome: https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
    - Tampermonkey for Edge: https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd

3. Install the user script mentioned, which can be installed directly by clicking here: https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3/raw/viewimage.user.js

**Comment by zleonov** [comment] 2023-03-21 21:39
@bijij I guess it's in your hands :)

**Comment by mzso** [comment] 2023-04-10 00:00
[**@ner00**](https://github.com/ner00) commented on [Mar 20, 2023, 3:04 PM GMT+1](https://github.com/bijij/ViewImage/issues/268#issuecomment-1476294452 "2023-03-20T14:04:25Z - Replied by Github Reply Comments"):
> In the meantime, I updated the script to be used with extensions such as GreaseMonkey, TamperMonkey, etc. You can grab the script here: [https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3](https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3)
> 
> **NOTE:** The script linked above will **not** work if the extension is running at the same time. While the extension isn't updated, you can disable it and use the script instead.
> 

Thanks! This seems to work fine. It even helps with the failure of loading high res images for the preview, I only got ridiculously pixellated ones for most pictures. (Either this or the addon broke it before.)

**Comment by ner00** [comment] 2023-04-10 00:39
> It even helps with the failure of loading high res images for the preview, I only got ridiculously pixellated ones for most pictures.

The script is almost a 1:1 of the add-on, I think that what is happening in those situations is that Google is linking a lowres preview, embedded or otherwise, for whatever reason. 

Someone had complained about this in relation to the add-on and the example they game me, when inspected, showed that Google wasn't previewing the endpoint image either which made it impossible for the add-on to do what Google itself doesn't.

Anyway, glad that at least the button is working for you.

**Comment by mzso** [comment] 2023-04-10 18:42
[**@ner00**](https://github.com/ner00) commented on [Apr 10, 2023, 2:39 AM GMT+2](https://github.com/bijij/ViewImage/issues/268#issuecomment-1501256208 "2023-04-10T00:39:23Z - Replied by Github Reply Comments"):
> > It even helps with the failure of loading high res images for the preview, I only got ridiculously pixellated ones for most pictures.
> 
> The script is almost a 1:1 of the add-on, I think that what is happening in those situations is that Google is linking a lowres preview, embedded or otherwise, for whatever reason. 
> 
> Someone had complained about this in relation to the add-on and the example they game me, when inspected, showed that Google wasn't previewing the endpoint image either which made it impossible for the add-on to do what Google itself doesn't.
> 
> Anyway, glad that at least the button is working for you.
> 
> _Originally posted by @ner00 in https://github.com/bijij/ViewImage/issues/268#issuecomment-1501256208_

No. I actually meant that the preview _were_ low res before. Now with your updated script I typically get proper high-res ones.

I checked right now, and I also get high res previews with the most part. So I guess the addon failing broke this as well. (Or my impressions are wrong, which is always possible...)

**Comment by ner00** [comment] 2023-04-10 18:45
> So I guess the addon failing broke this as well

This is a possibility, I only used the "broken" add-on for about 30 minutes, so I might have completely missed a collateral like that.

**Comment by apampuch** [comment] 2023-04-13 05:14
I'm not seeing the button at all, logged in OR logged out.

**Comment by softyoda** [comment] 2023-04-13 08:54
Same for me, firefox last version, on google up to data page, on windows 10 x64 architecture, with the firefox addon up to date.

**Comment by CarlosTorch** [comment] 2023-04-14 04:09
> In the meantime, I updated the script to be used with extensions such as GreaseMonkey, TamperMonkey, etc. You can grab the script here: https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3
> 
> **NOTE:** The script linked above will **not** work if the extension is running at the same time. While the extension isn't updated, you can disable it and use the script instead.
> 
> For those who might not know how to install user scripts to run in your browser, like an extension, follow this:
> 
>     1. Make sure to disable or uninstall the View Image extension in your browser (go to settings, find the section with extensions, and disable or uninstall it).
>        
>        * Firefox extensions URL: `about:addons`
>        * Chrome extensions URL: `chrome://extensions/`
>        * Edge extensions URL: `edge://extensions/`
> 
>     2. Install an extension that allows to add user scripts, most popular are Tampermonkey and Greasemonkey (choose one):
>        
>        * Tampermonkey for Firefox: https://addons.mozilla.org/firefox/addon/tampermonkey/
>        * Greasemonkey for Firefox: https://addons.mozilla.org/firefox/addon/greasemonkey/
>        * Tampermonkey for Chrome: https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
>        * Tampermonkey for Edge: https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd
> 
>     3. Install the user script mentioned, which can be installed directly by clicking here: https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3/raw/viewimage.user.js

works great, thanks

**Comment by raniesantos** [comment] 2023-04-23 08:59
Is bijij out on vacation?

**Comment by ner00** [comment] 2023-04-23 15:03
> Is bijij out on vacation?

Doesn't look like it since he has been active on other projects, maybe he got bored with this or maybe he's waiting for something.

**Comment by Reonu** [comment] 2023-04-29 10:30
@bijij hi, is this project still in development?

**Comment by absay** [comment] 2023-05-16 21:23
Any notable forks that are in active development?

Seems like this add-on is dead.

**Comment by ner00** [comment] 2023-05-16 21:28
> Any notable forks that are in active development? Or similar add-ons at least?

Use the updated userscript that I'm maintaining https://github.com/bijij/ViewImage/issues/268#issuecomment-1476294452

**Comment by bijij** [comment] 2023-05-18 05:24
> @bijij hi, is this project still in development?

Hi yes, sorry I've been somewhat busy recently.
I'm hoping to push out a new version end of week.

Though google and Mozilla may take more than a week to review and approve the update.

Unfortunately the issue still isn't occurring on any of my Google accounts so haven't been able to test it but I'll (assuming it's okay) base changes off what @ner00's done.

Thanks all.

**Comment by ner00** [comment] 2023-05-18 11:23
Myself and some of the users have had success with those changes after I was able to reproduce the issue, seems to be working so far. The most recent complaints seem to be from users who are not aware of the userscript and probably expected an update to the extension would have automatically happened by now.

One thing I have noticed lately, which I am not sure if it's new in general or not, is that often times I won't get the button to show because Google itself will only have a lowres base64 embed instead of an actual source link to the full image. 

Some of these cases seem to be in social media sites or the likes that probably have some form of no-crawling policy or w/e.

**Comment by ner00** [comment] 2023-05-22 19:52
Just tried it, works fine with Chrome! 

Note: class `r48jcc` for image source and `Rp89He` for _Visit_ button.

**Comment by gioxx** [comment] 2023-05-25 07:23
> I've updated to 3.7.0 on Firefox but it still doesn't work. Any Firefox users can confirm?

Firefox Nightly (115.0a1 (2023-05-24) (64 bit)) with View Image 3.7.0, seems to work perfectly
![immagine](https://github.com/bijij/ViewImage/assets/1768601/0d81279a-85f5-4441-ab81-5e2c96ceedda)

**Comment by gioxx** [comment] 2023-05-25 08:10
> Sorry, I forgot it doesn't work if the images are from instagram. Other websites work just fine.
> 
> Thanks

Yes, in this case I can confirm the problem using UserScript version updated by @ner00 and also the official addon (3.7.0) by @bijij.

**Comment by ner00** [comment] 2023-05-25 09:04
> Yes, in this case I can confirm the problem using UserScript version updated by @ner00 and also the official addon (3.7.0) by @bijij.

This is probably because Instagram (and Facebook to some extent) can deny crawling profiles' content, although Google still ends up providing an embedded base64 miniature. This is likely to become increasingly common, particularly with regards to privacy laws cracking down on the scope of crawling done to social media platforms.

I tested the Firefox extension too and there are two things I notice in comparison to Chrome's (and possibly other Chromium-based browsers in general):
- Sometimes the "View image" button doesn't show up on the first page load, you need to switch to a different image and back for the script to properly place the button element;
- The 'Search by image' option in the context menu (right-click over image) doesn't seem to work in Firefox, although it works fine in Chrome.

This last one isn't a deal breaker given that Google now includes the camera icon in the bottom left of all images which pretty much achieves the same purpose as the context-menu option. Still, I'm mentioning it because it works in Chrome but not FF.

**Comment by ner00** [comment] 2023-07-10 17:04
New class for the _Visit_ button: `e0XTue` - according to https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3?permalink_comment_id=4624558#gistcomment-4624558

**Comment by zleonov** [comment] 2023-07-10 18:09
Something very weird is going on. The view image button is gone, because of
the new class as @ner0 said.

But, now, I can right-click on the image now, and just click "Open Image in
New Tab" (FireFox) and it opens the full-resolution image. When I am not
logged in using Edge, the image button is still there (I guess getting the
old class there) but I can still right-click and open the image in a new
tab, and it shows the full-resolution image.

**Comment by ner00** [comment] 2023-07-10 19:57
> now, I can right-click on the image now, and just click "Open Image in New Tab" (FireFox) and it opens the full-resolution image

This has worked for me for a long time, both in Firefox and Chrome, although I can't precise since when. 
A couple reasons why I don't use the right-click often in Google images:
- Requires two clicks instead of one;
- More often than not I mistakenly click on "Open link in New Tab" instead of "Open image in New Tab"

It's still better than nothing though.

**Comment by zleonov** [comment] 2023-07-10 21:35
@ner0 My memory must be playing tricks on me. If this is the case, isn't it
easier to make an addon that reasigns like, the middle click button to open
images in a new tab? or something? if it works consistently?

 I open images in a new tab a lot, i was thinking i want a shortcut anyway.

**Comment by ner00** [comment] 2023-07-10 21:53
I would assume that making an addon to reassign whatever action to open the image in a new tab would take a similar approach as the current one. After all, the only difference would be the button itself, but it would still always need to scan the page and use pretty much the same elements as anchors to extract the URL and use it inside the action.

**Comment by zleonov** [comment] 2023-07-10 22:21
@ner0 I was thinking that "Open Image in New Tab" already exists in the
firefox context menu. For any image, regardless of the website. Simply
re-assign that functionality. I am not well versed in the add-on APIs and
if that's possible.

**Comment by horse14t** [comment] 2023-08-09 20:22
@ner00 Thank you!!!
Though I noticed that the script doesn't work with this new Google update that displays multiple images.
![Capture](https://github.com/bijij/ViewImage/assets/43920874/08ac727b-e481-44c5-bf33-e36d35a4523e)

**Closed** 2023-09-02 02:26 UTC
Labels: bug
