### ISSUE TITLE
Stopped working suddenly 

### ISSUE THREAD

**Issue by zaid894** [bijij/ViewImage#196] opened 2019-10-28 13:55 UTC
not working at all , it was working 2 days ago.

**Comment by djkcel** [comment] 2019-10-28 14:03
Yes, stopped working after Chrome updated to latest version (78.0.3904.70) on Mac.

**Comment by Newcool1230** [comment] 2019-10-28 16:30
It also stopped working on Firefox 70.0 (64-bit)

**Comment by francwalter** [comment] 2019-10-29 10:14
Yes, not working anymore. And the other Add-On "Google images view images button" does not work neither.
Firefox 70 on Mac OS 10.11.6

**Comment by francwalter** [comment] 2019-10-29 10:18
... but the Add-On "Google Images Restoredby fanfare" is still working :)
https://addons.mozilla.org/en-US/firefox/addon/google-images-restored/

**Comment by KoteKotlyarov** [comment] 2019-10-29 12:48
Not working. Win10, Chrome 77.0.3865.120 x64

**Comment by jarayama** [comment] 2019-10-29 18:29
Same here macOs 10.14 chrome 77

**Comment by bijij** [comment] 2019-11-01 08:37
duplicate of #188

**Closed by bijij** 2019-11-01 08:37 UTC
Labels: bug, duplicate
