### ISSUE TITLE
View Image doesnt work in new G Images redesign

### ISSUE THREAD

**Issue by urboigrego** [bijij/ViewImage#161] opened 2018-08-31 01:47 UTC
Google recently implemented its new site redesign: the rounded edges design and the extension currently does not work.

thanks for the work
![image](https://user-images.githubusercontent.com/34886930/44942552-96ddc600-ade6-11e8-9486-83b007b2fa51.png)

**Comment by filips123** [comment] 2018-08-31 14:50
Possible duplicate of #112.

**Comment by bijij** [comment] 2018-09-01 14:43
Hi, I unfortantly can't do anything about this because I don't have the new design myself. 
So im going too need someone who has access to the new design work on this for me.

**Comment by urboigrego** [comment] 2018-09-01 14:45
Hello, i think the new design has not been fully rolled out, because 50% of
the other time, i get redirected to the old design

**Comment by qsniyg** [comment] 2018-09-04 13:18
I also don't have access, however I'm not sure how safe this is, but if you opened up an image like you did in the screenshot above, and then pressed F12->Elements tab, right clicked on the <html> element->Copy->Copy outerHTML, and then pasted to pastebin.com or similar (and pasted the link here), I would try to find a way to make it work :)

**Comment by Scott274** [comment] 2018-09-12 05:35
It's almost 2 weeks now this extension is broken....Google Images seems to have slightly modified it's site design again (the "Visit" link row is at the bottom again now)....is there going to be a fix!!!

**Comment by filips123** [comment] 2018-09-12 13:08
I think that fix will not be possible without new page design source code. Also, @bijij should probably wait until all people get new design because Gogole is changing it fast.

> I also don't have access, however I'm not sure how safe this is, but if you opened up an image like you did in the screenshot above, and then pressed F12->Elements tab, right clicked on the element->Copy->Copy outerHTML, and then pasted to pastebin.com or similar (and pasted the link here), I would try to find a way to make it work :)

@qsniyg  Other solution to get source code is to add `view-source:` before the URL (for example `view-source:https://www.google.com/`)

@urboigrego @Scott274 Please do what I or @qsniyg suggested. You will help to make the new design work earlier.

**Comment by bijij** [comment] 2018-09-12 13:41
> It's almost 2 weeks now this extension is broken....Google Images seems to have slightly modified it's site design again (the "Visit" link row is at the bottom again now)....is there going to be a fix!!!

@Scott274 I unfortuantely cannot fix this as I don't have access to this modified design. it seems they're selecting users at random to recieve it.

**Comment by urboigrego** [comment] 2018-09-13 03:36
[overdue screenshot.](https://imgur.com/JcRfnJc)

It's worth mentioning that I live in SE Asia and maybe the change it is geologically based?
Nope. tried with my girlfriend's laptop, she has the old design.

Here is the new page design source code 
[view-source:](https://paste.ee/p/7EUPj)
[copyOuterHTML](https://paste.ee/p/kOFDX)

**Comment by qsniyg** [comment] 2018-09-14 00:45
@filips123 The reason I suggested the roundabout method is because the popup itself needs to be captured. `view-image:` does not contain the code, at least not in an easily-testable way.

@urboigrego Thank you very much, I managed to get it to work with the source you have sent :)

**Closed** 2018-09-14 08:31 UTC
Labels: help wanted
